### ISSUE TITLE
Crash when a marine dies

### ISSUE THREAD

**Issue by jamie-34254** [MlemandPurrs/raplusmod#3]
```
OpenRA engine version release-20200503
Red Alert Plus (Full) mod version v.1.3.7-beta-full
on map 8ce4f98a9bb2ff738814e83de2c1cf49c100ccd2 (Unconventional Warfare by PizzaAtomica).
Date: 2020-09-10 19:39:03Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Unit `e1.marine` does not have a sequence named `rot3`
   at OpenRA.Graphics.SequenceProvider.GetSequence(String unitName, String sequenceName)
   at OpenRA.Graphics.Animation.PlaySequence(String sequenceName)
   at OpenRA.Graphics.Animation.PlayThen(String sequenceName, Action after)
   at OpenRA.Mods.Common.Effects.SpriteEffect.Tick(World world)
   at OpenRA.WorldUtils.DoTimed[T](IEnumerable`1 e, Action`1 a, String text)
   at OpenRA.World.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.RunGame(String[] args)
```

**Comment by MlemandPurrs** [comment]
Hmm, i see Marine was missing rotting Infantry sequence.

**Comment by MlemandPurrs** [comment]
made a new release that is supposed to get it fixed:
https://github.com/MlemandPurrs/raplusmod/releases/tag/v.1.3.8-crashfixes
tell me again if its still occuring.

**Comment by jamie-34254** [comment]
Looks to be fixed
