### ISSUE TITLE
Crashes using Ukrain 

### ISSUE THREAD

**Issue by olliewuk** [MlemandPurrs/raplusmod#5]
Map: Poland Raid
Faction: Ukrain

Had just built a Naval base

OpenRA engine version release-20200503
Red Alert Plus (Full) mod version v.1.3.8-crashfixes
on map 1538dc15addff50b6e42fa92ea48ebf7ba79c6f5 (Poland Raid by s1w).
Date: 2020-09-17 20:00:31Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.Collections.Generic.KeyNotFoundException`: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at OpenRA.Mods.Common.Traits.SpawnMPUnits.SpawnUnitsForPlayer(World w, Player p, CPos sp)
   at OpenRA.Mods.Common.Traits.SpawnMPUnits.WorldLoaded(World world, WorldRenderer wr)
   at OpenRA.World.LoadComplete(WorldRenderer wr)
   at OpenRA.Game.StartGame(String mapUID, WorldType type)
   at OpenRA.Network.UnitOrders.ProcessOrder(OrderManager orderManager, World world, Int32 clientId, Order order)
   at OpenRA.Network.OrderManager.TickImmediate()
   at OpenRA.Sync.<>c__DisplayClass13_0.<RunUnsynced>b__0()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.RunGame(String[] args)

**Comment by jamie-34254** [comment]
I think this is related:
`Exception of type System.InvalidOperationException: Unit bsub does not have a sequence named icon`

**Comment by MlemandPurrs** [comment]
for some reason there was an 2 behind the bsubicon, fixed

**Comment by olliewuk** [comment]
Amazing. thank you
